### ISSUE TITLE
Add windows support using pnet

### ISSUE THREAD

**Issue by sigmaSd** [skylinecc/ipmap#3]
It should be simple https://github.com/imsnif/bandwhich/blob/main/src/network/sniffer.rs

**Comment by sigmaSd** [comment]
Here is a poe https://github.com/skylinecc/ipmap/compare/main...sigmaSd:main (the mac and widnows needs some minor fixes to build)

Actually I'm probably going to open an issue on bandwhich to see if we can librify parts of it, but it will probably take time

**Comment by sigmaSd** [comment]
I made an experimental lib out of bandwhich https://github.com/sigmaSd/sniff (macors/win error compilation fixed but I still didn't test them but they should work)
here is the diff using it https://github.com/skylinecc/ipmap/compare/main...sigmaSd:poe2?expand=1

**Comment by DefunctLizard** [comment]
I don't run windows as of right now, but you are welcome to make a pull request once you are done and we can bring it in. Thanks for the work!

**Comment by sigmaSd** [comment]
I'm probably going to wait for bandwhich maitainer opinion https://github.com/imsnif/bandwhich/issues/198

Other then that this https://github.com/skylinecc/ipmap/compare/main...sigmaSd:poe2?expand=1 already works on linux and probably on all platforms (I'll test windows shortly)

**Comment by DefunctLizard** [comment]
I'm so happy you're working on this! I am going to be splitting things up this week with the project. This means allowing different methods of capturing packets and different services for geolocation.

I will start working on a command line option for different methods of capturing packets like you are doing.

Once again, I'm so glad you like our project! 😁😁😁😁😁

**Comment by sigmaSd** [comment]
@DefunctLizard Yes I forgot to say this is a really cool project!

**Comment by DefunctLizard** [comment]
Ultimately, the base of ipmap already supports Windows. You just need to install WinPcap.

More info on the `pcap` library page (what we use) https://crates.io/crates/pcap

**Comment by sigmaSd** [comment]
Ah indeed, and apparently the author is working on it again, since there are recent commits here https://github.com/ebfull/pcap, (the crate io verison is from 2017).

The difference is that https://github.com/libpnet/libpnet is a pure rust implementation (instead of bindings in the case of pnet)

So your project probably already supports windows, well my bad then!

I'll close the issue since its not correct anymore and if the sniffing crate idea works and I'll open a PR to add an extra backend

**Comment by sigmaSd** [comment]
You should probably add a note that windows support require git version of pcap till they release the 0.8.0 version

**Comment by DefunctLizard** [comment]
I'll add that, thanks!
